framework: mocha

src_files:
  - lib/**/*.js
  - test/**/*.coffee

serve_files:
  - build/**/*.js

before_tests: ./node_modules/.bin/webpack --config webpack.test.config.js

launch_in_dev:
  - chrome
  - safari
  - firefox
